# Generated by Django 3.1.2 on 2020-10-05 20:07
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spent',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='spent',
            name='spent',
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name='Gasto'
            ),
        ),
        migrations.AlterField(
            model_name='spent',
            name='value',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                verbose_name='Valor',
            ),
        ),
    ]
