# Generated by Django 3.1.2 on 2020-10-11 00:00
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201010_2058'),
        ('core', '0002_auto_20201005_1707'),
    ]

    operations = []
