# Generated by Django 3.1.2 on 2020-10-12 19:17
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_merge_20201010_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'income',
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name='Renda Bruta Mensal',
                    ),
                ),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='income',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Renda Mensal Bruta',
                'verbose_name_plural': 'Rendas Mensais Brutas',
                'ordering': ('-id',),
            },
        ),
    ]
