# Generated by Django 3.1.2 on 2020-10-13 00:36
import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='save_percent',
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.MinValueValidator(1),
                ],
                verbose_name='Pocentagem Ah Economizar',
            ),
        ),
    ]
