# Generated by Django 3.1.2 on 2020-11-15 03:09
import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_income_save_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='income',
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                verbose_name='Renda Bruta Mensal',
            ),
        ),
        migrations.AlterField(
            model_name='income',
            name='save_percent',
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.MinValueValidator(0),
                ],
                verbose_name='Pocentagem Ah Economizar',
            ),
        ),
    ]
