# Generated by Django 3.1.2 on 2020-11-26 21:27
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_auto_20201115_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name='Criado',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='month',
            field=models.IntegerField(default=11, verbose_name='Mês'),
        ),
        migrations.AddField(
            model_name='income',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado'),
        ),
        migrations.AddField(
            model_name='income',
            name='year',
            field=models.IntegerField(default=2020, verbose_name='Ano'),
        ),
        migrations.AddField(
            model_name='spent',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name='Criado',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado'),
        ),
        migrations.AlterField(
            model_name='income',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='income',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
