# Generated by Django 3.1.2 on 2020-11-26 21:44
import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201126_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='income',
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Renda Bruta Mensal',
            ),
        ),
    ]
