# Generated by Django 3.1.3 on 2020-11-29 04:13
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201126_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='spent',
            name='month',
            field=models.IntegerField(default=11, verbose_name='Mês'),
        ),
        migrations.AddField(
            model_name='spent',
            name='year',
            field=models.IntegerField(default=2020, verbose_name='Ano'),
        ),
    ]
