# Generated by Django 3.1.3 on 2020-11-30 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201129_0113'),
    ]

    operations = [
        migrations.AlterField(
                model_name='spent',
                name='value',
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=15,
                null=True,
                verbose_name='Valor',
            ),
        ),
    ]
