# Generated by Django 3.1.3 on 2020-12-01 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201129_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='spent',
            name='fixed_account',
            field=models.BooleanField(default=False, verbose_name='Conta fixa'),
        ),
    ]
