# Generated by Django 3.1.3 on 2020-12-29 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20201220_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spent',
            name='date',
        ),
    ]
